insert into COURSE (id, course, description) values (1, 'WFC', 'accumsan tortor quis');
insert into COURSE (id, course, description) values (2, 'HP Procurve Networking', 'magnis dis parturient montes nascetur');
insert into COURSE (id, course, description) values (3, 'Hospitality Industry', 'ac enim in');
insert into COURSE (id, course, description) values (4, 'ODBC', 'maecenas tristique est et tempus');
insert into COURSE (id, course, description) values (5, 'Wine Tasting', 'in felis donec');
insert into COURSE (id, course, description) values (6, 'VT', 'mauris enim leo rhoncus');
insert into COURSE (id, course, description) values (7, 'BBEdit', 'felis ut at');
insert into COURSE (id, course, description) values (8, 'WSGI', 'lacus curabitur at');
insert into COURSE (id, course, description) values (9, 'Electric Guitar', 'integer a nibh in quis');
insert into COURSE (id, course, description) values (10, 'IP PBX', 'duis consequat dui nec');
insert into COURSE (id, course, description) values (11, 'SRM', 'ridiculus mus vivamus vestibulum sagittis');
insert into COURSE (id, course, description) values (12, 'Httpd', 'arcu libero rutrum ac lobortis');
insert into COURSE (id, course, description) values (13, 'Observation', 'tempus sit amet');
insert into COURSE (id, course, description) values (14, 'IO', 'lectus pellentesque eget nunc');
insert into COURSE (id, course, description) values (15, 'NHL', 'ipsum aliquam non');
insert into COURSE (id, course, description) values (16, 'VSAT', 'eget congue eget semper');
insert into COURSE (id, course, description) values (17, 'Museums', 'orci pede venenatis');
insert into COURSE (id, course, description) values (18, 'PMCS', 'orci vehicula condimentum curabitur');
insert into COURSE (id, course, description) values (19, 'IFW', 'lectus in est risus auctor');
insert into COURSE (id, course, description) values (20, 'Portraits', 'dapibus at diam');
insert into COURSE (id, course, description) values (21, 'Whitewater Kayaking', 'nulla nisl nunc nisl');
insert into COURSE (id, course, description) values (22, 'IPS', 'faucibus orci luctus et ultrices');
insert into COURSE (id, course, description) values (23, 'Oligonucleotides', 'non sodales sed tincidunt eu');
insert into COURSE (id, course, description) values (24, 'PVST+', 'dui maecenas tristique');
insert into COURSE (id, course, description) values (25, 'Oracle ERP', 'habitasse platea dictumst');
insert into COURSE (id, course, description) values (26, 'Soft Skills', 'habitasse platea dictumst');
insert into COURSE (id, course, description) values (27, 'Aircraft Systems', 'lobortis ligula sit amet');
insert into COURSE (id, course, description) values (28, 'Talent Acquisition', 'id ornare imperdiet');
insert into COURSE (id, course, description) values (29, 'Whiplash', 'phasellus in felis donec semper');
insert into COURSE (id, course, description) values (30, 'DCOM', 'erat id mauris vulputate elementum');
insert into COURSE (id, course, description) values (31, 'Keyshot', 'velit vivamus vel nulla');
insert into COURSE (id, course, description) values (32, 'PGA', 'ut rhoncus aliquet');
insert into COURSE (id, course, description) values (33, 'MPE', 'felis donec semper sapien a');
insert into COURSE (id, course, description) values (34, 'Zillow', 'in consequat ut nulla');
insert into COURSE (id, course, description) values (35, 'XCAP', 'id consequat in consequat');
insert into COURSE (id, course, description) values (36, 'DMS-100', 'quis libero nullam');
insert into COURSE (id, course, description) values (37, 'Layout', 'sem sed sagittis nam congue');
insert into COURSE (id, course, description) values (38, 'EU Funding', 'pede venenatis non sodales sed');
insert into COURSE (id, course, description) values (39, 'Ultiboard', 'curabitur at ipsum');
insert into COURSE (id, course, description) values (40, 'DMEDI', 'in quam fringilla');
insert into COURSE (id, course, description) values (41, 'American Literature', 'quam pede lobortis ligula sit');
insert into COURSE (id, course, description) values (42, 'VBAC', 'massa volutpat convallis morbi odio');
insert into COURSE (id, course, description) values (43, 'Mac OS X Server', 'nec nisi vulputate nonummy maecenas');
insert into COURSE (id, course, description) values (44, 'VCI', 'justo morbi ut');
insert into COURSE (id, course, description) values (45, 'OA Framework', 'nunc vestibulum ante');
insert into COURSE (id, course, description) values (46, 'Quantitative Finance', 'vestibulum sit amet cursus');
insert into COURSE (id, course, description) values (47, 'TFF', 'nam congue risus');
insert into COURSE (id, course, description) values (48, 'Knowledge Transfer', 'neque duis bibendum morbi non');
insert into COURSE (id, course, description) values (49, 'SFP', 'ac tellus semper');
insert into COURSE (id, course, description) values (50, 'DVD Architect', 'morbi a ipsum integer');
insert into COURSE (id, course, description) values (51, 'Norton Utilities', 'justo sollicitudin ut');
insert into COURSE (id, course, description) values (52, 'Klarity', 'quisque arcu libero rutrum ac');
insert into COURSE (id, course, description) values (53, 'Administration', 'nibh in lectus');
insert into COURSE (id, course, description) values (54, 'Cytology', 'adipiscing elit proin interdum');
insert into COURSE (id, course, description) values (55, 'Satellite TV', 'at nibh in hac habitasse');
insert into COURSE (id, course, description) values (56, 'LS-DYNA', 'nisi volutpat eleifend donec');
insert into COURSE (id, course, description) values (57, 'Water Quality', 'lacinia aenean sit');
insert into COURSE (id, course, description) values (58, 'Buyer&#39;s Agent', 'nunc nisl duis bibendum felis');
insert into COURSE (id, course, description) values (59, 'Kanban', 'maecenas leo odio condimentum id');
insert into COURSE (id, course, description) values (60, 'Visual Studio', 'platea dictumst aliquam');
insert into COURSE (id, course, description) values (61, 'JGroups', 'volutpat sapien arcu sed');
insert into COURSE (id, course, description) values (62, 'Biostatistics', 'eros elementum pellentesque quisque porta');
insert into COURSE (id, course, description) values (63, 'GFAAS', 'amet sapien dignissim vestibulum vestibulum');
insert into COURSE (id, course, description) values (64, 'GSA Contracting', 'vivamus vel nulla eget');
insert into COURSE (id, course, description) values (65, 'PTO', 'sed sagittis nam congue risus');
insert into COURSE (id, course, description) values (66, 'CQI', 'commodo placerat praesent');
insert into COURSE (id, course, description) values (67, 'Drainage', 'penatibus et magnis dis');
insert into COURSE (id, course, description) values (68, 'Management Consulting', 'nec molestie sed');
insert into COURSE (id, course, description) values (69, 'HSSE', 'vestibulum sit amet cursus id');
insert into COURSE (id, course, description) values (70, 'SQL Azure', 'ut massa quis augue');
insert into COURSE (id, course, description) values (71, 'Conservation Issues', 'sem sed sagittis nam');
insert into COURSE (id, course, description) values (72, 'Iron Ore', 'nonummy integer non velit donec');
insert into COURSE (id, course, description) values (73, 'Luxury Brand Marketing', 'felis donec semper sapien');
insert into COURSE (id, course, description) values (74, 'Sony Vegas', 'at nibh in hac');
insert into COURSE (id, course, description) values (75, 'Toad', 'eu felis fusce');
insert into COURSE (id, course, description) values (76, 'Small Business Lending', 'lacus curabitur at ipsum');
insert into COURSE (id, course, description) values (77, 'Fermentation', 'in congue etiam justo');
insert into COURSE (id, course, description) values (78, 'BSC', 'vitae consectetuer eget rutrum at');
insert into COURSE (id, course, description) values (79, 'Ambulance', 'semper est quam pharetra');
insert into COURSE (id, course, description) values (80, 'Broadcast', 'dui vel nisl duis');
insert into COURSE (id, course, description) values (81, 'FFA', 'elit proin risus');
insert into COURSE (id, course, description) values (82, 'PCIe', 'morbi ut odio');
insert into COURSE (id, course, description) values (83, 'Petrochemical', 'quis orci nullam molestie');
insert into COURSE (id, course, description) values (84, 'Switching', 'consequat ut nulla sed accumsan');
insert into COURSE (id, course, description) values (85, 'FP7', 'auctor sed tristique in tempus');
insert into COURSE (id, course, description) values (86, 'Equity Research', 'dignissim vestibulum vestibulum');
insert into COURSE (id, course, description) values (87, 'Professional Services', 'rutrum ac lobortis vel');
insert into COURSE (id, course, description) values (88, 'Xero', 'semper est quam pharetra magna');
insert into COURSE (id, course, description) values (89, 'Broadcast Journalism', 'sit amet nulla');
insert into COURSE (id, course, description) values (90, 'AXI', 'sapien arcu sed augue aliquam');
insert into COURSE (id, course, description) values (91, 'NC-Verilog', 'nulla eget eros');
insert into COURSE (id, course, description) values (92, 'Compliance Oversight', 'orci nullam molestie nibh');
insert into COURSE (id, course, description) values (93, 'EIP', 'scelerisque mauris sit amet');
insert into COURSE (id, course, description) values (94, 'Oracle Identity Manager', 'nam nulla integer');
insert into COURSE (id, course, description) values (95, 'Hotels', 'in est risus auctor sed');
insert into COURSE (id, course, description) values (96, 'GI', 'enim in tempor turpis');
insert into COURSE (id, course, description) values (97, 'QEMU', 'gravida sem praesent id massa');
insert into COURSE (id, course, description) values (98, 'Patient Advocacy', 'vulputate elementum nullam varius');
insert into COURSE (id, course, description) values (99, 'Renewable Energy', 'lacus curabitur at ipsum ac');
insert into COURSE (id, course, description) values (100, 'OMT', 'platea dictumst morbi vestibulum velit');
